import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Edu_NSW_ACT_Hand_Pre } from "next/font/google"; 

const edu = Edu_NSW_ACT_Hand_Pre({
  subsets: ["latin"],
  weight: ["400", "700"], 
  variable: "--font-edu",
});

const geistSans = Geist({
  variable: "--font-geist-sans",  
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "PixelPal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}  ${edu.variable}`}>
        {children}
      </body>
    </html>
  );
}
